package hu.distributeddocumentor.gui;

import java.awt.event.KeyEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * Panel which docks to the bottom of the text editor window and provides
 * find in text functionality
 * @author Daniel Vigovszky
 */
public class FindInTextPanel extends javax.swing.JPanel {

    private FindInTextListener listener;
    
    /**
     * Creates new form FindInTextPanel
     */
    public FindInTextPanel() {
        initComponents();
        
        tbInput.getDocument().addDocumentListener(
                new DocumentListener() {                

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateButtons();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateButtons();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateButtons();
            }
            
            private void updateButtons() {
                btFind.setEnabled(tbInput.getText().length() > 0);
            }
        });
    }

    public FindInTextListener getListener() {
        return listener;
    }

    public void setListener(FindInTextListener listener) {
        this.listener = listener;
    }       

    @Override
    public void requestFocus() {
        tbInput.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbInput = new javax.swing.JTextField();
        btFind = new javax.swing.JButton();
        btClose = new javax.swing.JButton();

        tbInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbInputKeyPressed(evt);
            }
        });

        btFind.setText("Find");
        btFind.setEnabled(false);
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        btClose.setText("X");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btClose))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tbInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btFind)
                .addComponent(btClose))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        
        if (listener != null) {
            listener.findNext(tbInput.getText());
        }        
    }//GEN-LAST:event_btFindActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        
        if (listener != null) {
            listener.finish();
        }        
    }//GEN-LAST:event_btCloseActionPerformed

    private void tbInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbInputKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btFindActionPerformed(null);
        }
        else if (evt.getKeyChar() == KeyEvent.VK_ESCAPE) {
            btCloseActionPerformed(null);
        }
        
    }//GEN-LAST:event_tbInputKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btFind;
    private javax.swing.JTextField tbInput;
    // End of variables declaration//GEN-END:variables
}
