package hu.distributeddocumentor.gui;

import hu.distributeddocumentor.model.Page;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.Point;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.net.URI;
import java.nio.charset.Charset;
import java.util.Iterator;
import java.util.Observable;
import java.util.Observer;
import org.apache.commons.lang3.StringEscapeUtils;
import org.w3c.dom.Element;
import org.xhtmlrenderer.render.Box;
import org.xhtmlrenderer.simple.FSScrollPane;
import org.xhtmlrenderer.simple.XHTMLPanel;
import org.xhtmlrenderer.swing.BasicPanel;
import org.xhtmlrenderer.swing.FSMouseListener;
import org.xhtmlrenderer.swing.LinkListener;
import org.xhtmlrenderer.swing.NaiveUserAgent;

public class HTMLPreview extends javax.swing.JPanel implements Observer, PreviewSync {

    private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(HTMLPreview.class.getName());
    private final Page page;
    private final File root;
    private final FSScrollPane scrollPane;
    private final XHTMLPanel htmlPanel;
    
    
    /**
     * Creates new form HTMLPreview
     */
    public HTMLPreview(Page page, final PageEditorHost host, File root) {
        initComponents();
        
        this.page = page;
        this.root = root;                
        
        htmlPanel = new XHTMLPanel();
        htmlPanel.setVisible(true);
        
        scrollPane = new FSScrollPane(htmlPanel);
                
        add(scrollPane, BorderLayout.CENTER);
        
        NaiveUserAgent uac = new NaiveUserAgent();
        
        final String rootUri = root.toURI().toString();
        uac.setBaseURL(rootUri);
        
        htmlPanel.getSharedContext().setUserAgentCallback(uac);
        //htmlPanel.getSharedContext().setReplacedElementFactory(new SwingReplacedElementFactory());
        
        for (Object listener : htmlPanel.getMouseTrackingListeners())
            if (listener instanceof LinkListener)
                htmlPanel.removeMouseTrackingListener((FSMouseListener)listener);
        
        htmlPanel.addMouseTrackingListener(
                new LinkListener() {

                    @Override
                    public void linkClicked(BasicPanel panel, String uri) {
                        
                        if (!uri.startsWith("http://") && 
                            !uri.startsWith("https://") &&
                            !uri.startsWith("file://") &&
                             uri.length() > ".html".length()) {
                        
                            String id = uri.substring(0, uri.length() - ".html".length());
                            host.openOrFocusPage(id);
                            
                        } else if (uri.toString().startsWith(rootUri)) {
                            String fileName = uri.toString().substring(rootUri.length());
                            fileName = fileName.substring(0, fileName.length() - ".html".length());

                            host.openOrFocusPage(fileName);
                        } else {
                            try {
                                Desktop.getDesktop().browse(new URI(uri));
                            }
                            catch (Exception ex) {
                                logger.error(null, ex);
                            }
                        }                        
                    }                    
                });
        
        page.addObserver(this);
        
        renderPage();
    }

    @Override
    public void scrollToLine(int lineIdx) {
        
        String lineId = "line"+Integer.toString(lineIdx);
        
        Box rootBox = htmlPanel.getRootBox();
        if (rootBox != null) {
            Box lineAnnotation = findLineAnnotation(rootBox, lineId);

            if (lineAnnotation != null) {

                Point pt = new Point(lineAnnotation.getAbsX(), lineAnnotation.getAbsY());
                int top = scrollPane.getVerticalScrollBar().getValue();
                int bottom = top + scrollPane.getHeight();

                if (pt.y < top || pt.y > bottom)
                    htmlPanel.scrollTo(pt);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        renderPage();
    }//GEN-LAST:event_formComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    private void renderPage() {
        // Getting the HTML representation of the page
        String html = page.asAnnotatedHTMLembeddingCSS();
        byte[] htmlBytes = html.getBytes(Charset.forName("utf-8"));
        
        try {
            htmlPanel.setDocument(new ByteArrayInputStream(htmlBytes), root.toURI().toString());            
            
        } catch (Exception ex) {
            logger.error(null, ex);            
            
            String simpleHtml = page.asHTMLembeddingCSS();
            htmlBytes = simpleHtml.getBytes(Charset.forName("utf-8"));
        
            try {
                htmlPanel.setDocument(new ByteArrayInputStream(htmlBytes), root.toURI().toString());            

            } catch (Exception iex) {
            
                String errorHtml = "<?xml version='1.0' encoding='utf-8'?><html xmlns='http://www.w3.org/1999/xhtml'><body><h1>Failed to render page</h1><pre>"+
                                StringEscapeUtils.escapeXml(iex.toString())+
                                "</pre></body></html>";
            
                htmlBytes = errorHtml.getBytes(Charset.forName("utf-8"));
        
                try {
                    htmlPanel.setDocument(new ByteArrayInputStream(htmlBytes), root.toURI().toString());            

                } catch (Exception iiex) {
                    logger.error(null, iiex);            
                }
            }
        }
    }

    @Override
    public void update(Observable o, Object o1) {
        renderPage();
    }

    private Box findLineAnnotation(Box box, String lineId) {
        
        Element elem = box.getElement();
        if (elem != null) {
            if ("span".equals(elem.getNodeName()) &&
                elem.hasAttribute("id") &&
                elem.getAttribute("id").equals(lineId)) {
                return box;
            }
        }
        for (Iterator it = box.getChildIterator(); it.hasNext();) {
            Box child = (Box) it.next();
            Box result = findLineAnnotation(child, lineId);
            if (result != null)
                return result;
        }
        
        return null;
    }
}
