package hu.distributeddocumentor.gui;

import java.awt.event.KeyEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * Panel which is docked to the bottom of the text editor window and provides
 * search and replace functionality
 * @author Daniel Vigovszky
 */
public class ReplaceInTextPanel extends javax.swing.JPanel {

    private ReplaceInTextListener listener;
    
    /**
     * Creates new form ReplaceInTextPanel
     */
    public ReplaceInTextPanel() {
        initComponents();
        
        DocumentListener docListener = new DocumentListener() {                

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateButtons();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateButtons();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateButtons();
            };
        };
        
        tbInput.getDocument().addDocumentListener(docListener);
        tbOutput.getDocument().addDocumentListener(docListener);
    }

    public FindInTextListener getListener() {
        return listener;
    }

    public void setListener(ReplaceInTextListener listener) {
        this.listener = listener;
    }          
        
    private void updateButtons() {
        boolean hasInput = tbInput.getText().length() > 0; 
        boolean hasOutput = tbOutput.getText().length() > 0;
        boolean hasMatch = listener != null && listener.hasSelection(tbInput.getText());
        
        btFindNext.setEnabled(hasInput);
        btReplace.setEnabled(hasInput && hasOutput && hasMatch); 
        btReplaceAll.setEnabled(hasInput && hasOutput);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tbOutput = new javax.swing.JTextField();
        btFindNext = new javax.swing.JButton();
        btReplace = new javax.swing.JButton();
        btReplaceAll = new javax.swing.JButton();
        btClose = new javax.swing.JButton();

        tbInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbInputKeyPressed(evt);
            }
        });

        jLabel1.setText("to");

        tbOutput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbOutputKeyPressed(evt);
            }
        });

        btFindNext.setText("Find next");
        btFindNext.setEnabled(false);
        btFindNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindNextActionPerformed(evt);
            }
        });

        btReplace.setText("Replace");
        btReplace.setEnabled(false);
        btReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReplaceActionPerformed(evt);
            }
        });

        btReplaceAll.setText("Replace all");
        btReplaceAll.setEnabled(false);
        btReplaceAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReplaceAllActionPerformed(evt);
            }
        });

        btClose.setText("X");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(tbInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tbOutput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btFindNext)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btReplace)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btReplaceAll)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btClose, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(tbInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(btFindNext)
                .add(btClose)
                .add(btReplace)
                .add(btReplaceAll)
                .add(tbOutput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed

        if (listener != null) {
            listener.finish();
        }
    }//GEN-LAST:event_btCloseActionPerformed

    private void btFindNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindNextActionPerformed

        if (listener != null) {
            listener.findNext(tbInput.getText());
            updateButtons();
        }
    }//GEN-LAST:event_btFindNextActionPerformed

    private void tbInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbInputKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btFindNextActionPerformed(null);
        }
        else if (evt.getKeyChar() == KeyEvent.VK_ESCAPE) {
            btCloseActionPerformed(null);
        }

    }//GEN-LAST:event_tbInputKeyPressed

    private void btReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReplaceActionPerformed
        
        if (listener != null) {
            listener.replaceCurrent(tbOutput.getText());
            updateButtons();
        }        
    }//GEN-LAST:event_btReplaceActionPerformed

    private void btReplaceAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReplaceAllActionPerformed
        
        if (listener != null) {
            listener.replaceAll(tbInput.getText(), tbOutput.getText());
            updateButtons();
        }
    }//GEN-LAST:event_btReplaceAllActionPerformed

    private void tbOutputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbOutputKeyPressed
       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btReplaceActionPerformed(null);
        }
        else if (evt.getKeyChar() == KeyEvent.VK_ESCAPE) {
            btCloseActionPerformed(null);
        }
    }//GEN-LAST:event_tbOutputKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btFindNext;
    private javax.swing.JButton btReplace;
    private javax.swing.JButton btReplaceAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tbInput;
    private javax.swing.JTextField tbOutput;
    // End of variables declaration//GEN-END:variables
}
