package hu.distributeddocumentor.gui;

import hu.distributeddocumentor.model.Page;
import java.io.File;
import javax.swing.undo.UndoManager;

public class SplittedPageView extends javax.swing.JPanel {

    private final WikiMarkupEditor editor;
    private final NativeBrowserPreview preview;
    
    /**
     * Creates new form SplittedPageView
     */
    public SplittedPageView(Page page, File root, PageEditorHost host) {
        initComponents();
        
        editor = new WikiMarkupEditor(page, host);
        preview = new NativeBrowserPreview(page, host, root);
        
        jSplitPane1.setLeftComponent(editor);
        jSplitPane1.setRightComponent(preview);
        
        jSplitPane1.setDividerLocation(0.5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setResizeWeight(0.5);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    public UndoManager getEditorUndoManager() {
        return editor.getUndoManager();
    }

    void dispose() {
        preview.dispose();
    }
}
